name: Run Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # install the python version needed
          
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install tar make gcc
          
      - name: Install Python 3.8
        run: |
          wget https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tar.xz
          tar xf Python-3.8.5.tar.xz
          cd Python-3.8.5
          ./configure
          make
          sudo make install

      - name: install python packages
        run: |
          pip install -r requirements.txt
          
      - name: execute py script # run app.py
        env: 
          USCIS_CASE_ID: ${{ secrets.USCIS_CASE_ID }}
          TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
          TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
        run: python app.py
